version: "3.9"
services:
    postgres:
        image: postgres:16.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: file_processing_db
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
    rabbitmq:
        image: rabbitmq:latest
        hostname: rabbitmq
        restart: unless-stopped
        environment:
            TZ: Europe/Moscow
            RABBITMQ_DEFAULT_USER: rab
            RABBITMQ_DEFAULT_PASS: 1234
            RABBITMQ_DEFAULT_VHOST: vhost
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq￼
        ports:
            - "5672:5672"
            - "15672:15672"

volumes:
    postgres:
        driver: local