spring:
    servlet:
        multipart:
            max-file-size: 2MB
            max-request-size: 2MB
    output:
        ansi:
            enabled: always
    application:
        name: distributed-file-processing
    rabbitmq:
        host: localhost
        virtual-host: vhost
        password: 1234
        username: rab
        publisher-returns: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/file_processing_db
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: ${GOOGLE_OAUTH_CLIENT_ID}
                        clientSecret: ${GOOGLE_OAUTH_CLIENT_SECRET}

app:
    rabbitmq:
        exchange: exchange
        routing-key: process.file
        queue: process.file

logging:
    level:
        org.springframework.security: TRACE
        org.springframework.web: TRACE

