spring:
    profiles:
        active: dev
    application:
        name: distributed-file-processing
    output:
        ansi:
            enabled: always

springdoc:
    swagger-ui:
        path: /swagger-ui